version: '3.8'

services:
  postgres:
    container_name: test_db
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_test:/var/lib/postgresql/data/


volumes:
  pg_data_test:
