version: '3.8'

services:
  postgres:
    container_name: test_db
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data_test:/var/lib/postgresql/data/

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_HTTP_ADDR: ${MEILI_HTTP_ADDR}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    ports:
      - "${MEILI_PORT}:${MEILI_PORT}"
    volumes:
      - meili_data:/data.ms

volumes:
  pg_data_test:
  meili_data: