version: '3.8'

services:
  postgres:
    container_name: test_db
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_test:/var/lib/postgresql/data/


  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_HTTP_ADDR: 0.0.0.0:7700
      MEILI_MASTER_KEY: masterKey
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/data.ms

volumes:
  pg_data_test:
  meili_data:
